/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Expert
 */
public class BillInfo extends javax.swing.JFrame {
    
    DBConn DB = new DBConn();

    /**
     * Creates new form BillInfo
     */
    public BillInfo() {
        initComponents();
        
        //  CODE FOR DATE AND TIME
        
        Calendar c = Calendar.getInstance();
        String dd = String.valueOf(c.get(Calendar.DAY_OF_MONTH));
        String mm = String.valueOf(c.get(Calendar.MONTH)+1);
        String yy = String.valueOf(c.get(Calendar.YEAR));
        
        String hr = String.valueOf(c.get(Calendar.HOUR));
        String min = String.valueOf(c.get(Calendar.MINUTE));
        
        lblDATE.setText(dd+"/"+mm+"/"+yy+"\n  "+hr+":"+min);
        
        DB.opencon();
        ResultSet myrs;
        myrs = DB.select("select * from compshopitem");
        try {
            while(myrs.next())
            {
                cmbItemId.addItem(myrs.getString("ItemId"));
            }
            
        DB.closeCon();
        } catch (SQLException ex) 
        {
            Logger.getLogger(BillInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CID = new javax.swing.JLabel();
        TextCId = new javax.swing.JTextField();
        CContactNo = new javax.swing.JLabel();
        TextContactId = new javax.swing.JTextField();
        CContactNo1 = new javax.swing.JLabel();
        TextCName = new javax.swing.JTextField();
        CReceiptNo = new javax.swing.JLabel();
        CReceiptNo1 = new javax.swing.JLabel();
        TextCReceiptNo = new javax.swing.JTextField();
        lblDATE = new javax.swing.JLabel();
        RbtnCash = new javax.swing.JRadioButton();
        RbtnDebit = new javax.swing.JRadioButton();
        CReceiptNo2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        CContactNo2 = new javax.swing.JLabel();
        CContactNo3 = new javax.swing.JLabel();
        CContactNo4 = new javax.swing.JLabel();
        CContactNo5 = new javax.swing.JLabel();
        CContactNo6 = new javax.swing.JLabel();
        CContactNo7 = new javax.swing.JLabel();
        CContactNo8 = new javax.swing.JLabel();
        CContactNo9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCategory = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cmbItemId = new javax.swing.JComboBox<>();
        cmbQty = new javax.swing.JComboBox<>();
        CContactNo10 = new javax.swing.JLabel();
        CContactNo11 = new javax.swing.JLabel();
        CContactNo12 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        txtNetBill = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BILL COMP SHOP");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(153, 153, 153));

        CID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CID.setText("C ID : ");

        CContactNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo.setText("C Mo : ");

        CContactNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo1.setText("C Name : ");

        CReceiptNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CReceiptNo.setText("C Receipt No: ");

        CReceiptNo1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CReceiptNo1.setText("DATE ");

        lblDATE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        buttonGroup1.add(RbtnCash);
        RbtnCash.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RbtnCash.setText("CASH");
        RbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(RbtnDebit);
        RbtnDebit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RbtnDebit.setText("DEBIT");
        RbtnDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnDebitActionPerformed(evt);
            }
        });

        CReceiptNo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CReceiptNo2.setText("Payment Mode:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextContactId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CReceiptNo)
                                    .addComponent(CReceiptNo1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCReceiptNo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(lblDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TextCName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(232, 232, 232)
                                .addComponent(CReceiptNo2)
                                .addGap(131, 131, 131))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(703, 703, 703)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbtnDebit)
                            .addComponent(RbtnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CReceiptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextCReceiptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextContactId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CReceiptNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(RbtnCash))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CContactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextCName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(RbtnDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(CReceiptNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Price", "Category", "Brand", "QTY", "Unit", "Total"
            }
        ));
        jScrollPane1.setViewportView(Table);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(12, 167, 852, 151);

        CContactNo2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo2.setText("Item Id : ");
        jPanel3.add(CContactNo2);
        CContactNo2.setBounds(10, 30, 80, 36);

        CContactNo3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo3.setText("Item Name : ");
        jPanel3.add(CContactNo3);
        CContactNo3.setBounds(110, 30, 110, 36);

        CContactNo4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo4.setText("Category : ");
        jPanel3.add(CContactNo4);
        CContactNo4.setBounds(250, 30, 90, 36);

        CContactNo5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo5.setText("Unit: ");
        jPanel3.add(CContactNo5);
        CContactNo5.setBounds(370, 30, 70, 36);

        CContactNo6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo6.setText("Brand : ");
        jPanel3.add(CContactNo6);
        CContactNo6.setBounds(470, 30, 80, 36);

        CContactNo7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo7.setText("QTY: ");
        jPanel3.add(CContactNo7);
        CContactNo7.setBounds(690, 30, 70, 36);

        CContactNo8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo8.setText("Price : ");
        jPanel3.add(CContactNo8);
        CContactNo8.setBounds(580, 30, 98, 36);

        CContactNo9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo9.setText("Net Bill: ");
        jPanel3.add(CContactNo9);
        CContactNo9.setBounds(670, 410, 90, 40);

        txtTotal.setText("0");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotal);
        txtTotal.setBounds(770, 80, 80, 30);
        jPanel3.add(txtName);
        txtName.setBounds(119, 80, 100, 30);
        jPanel3.add(txtCategory);
        txtCategory.setBounds(240, 80, 100, 30);

        txtUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnitActionPerformed(evt);
            }
        });
        jPanel3.add(txtUnit);
        txtUnit.setBounds(350, 80, 100, 30);

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        jPanel3.add(txtBrand);
        txtBrand.setBounds(460, 80, 100, 30);
        jPanel3.add(txtPrice);
        txtPrice.setBounds(570, 80, 100, 30);

        cmbItemId.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemIdActionPerformed(evt);
            }
        });
        jPanel3.add(cmbItemId);
        cmbItemId.setBounds(10, 80, 80, 30);

        cmbQty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQtyActionPerformed(evt);
            }
        });
        jPanel3.add(cmbQty);
        cmbQty.setBounds(680, 80, 70, 30);

        CContactNo10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo10.setText("Total : ");
        jPanel3.add(CContactNo10);
        CContactNo10.setBounds(780, 30, 98, 36);

        CContactNo11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo11.setText("Sub Total : ");
        jPanel3.add(CContactNo11);
        CContactNo11.setBounds(670, 330, 100, 40);

        CContactNo12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CContactNo12.setText("Discount: ");
        jPanel3.add(CContactNo12);
        CContactNo12.setBounds(670, 370, 90, 40);

        txtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtSubTotal);
        txtSubTotal.setBounds(770, 340, 80, 30);

        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });
        jPanel3.add(txtDiscount);
        txtDiscount.setBounds(770, 380, 80, 30);

        txtNetBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetBillActionPerformed(evt);
            }
        });
        jPanel3.add(txtNetBill);
        txtNetBill.setBounds(770, 420, 80, 30);

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setOpaque(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd);
        btnAdd.setBounds(900, 80, 90, 40);

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  THANK YOU...VISIT AGAIN");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2);
        jLabel2.setBounds(390, 440, 270, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1101, 952));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cmbItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemIdActionPerformed
        try {
            // TODO add your handling code here:
            
            DB.opencon();
            
            ResultSet myrs1;
            myrs1 = DB.select("SELECT * FROM COMPSHOPITEM WHERE ITEMID= '"+ cmbItemId.getSelectedItem().toString()+ "' ");
            myrs1.next();
            txtName.setText(myrs1.getString("NAME"));
            txtCategory.setText(myrs1.getString("CATEGORY"));
            txtUnit.setText(myrs1.getString("UNITS"));
            txtBrand.setText(myrs1.getString("BRAND"));
            txtPrice.setText(myrs1.getString("PRICE"));
            
            DB.closeCon();
        } catch (SQLException ex) {
            Logger.getLogger(BillInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemIdActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubTotalActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void txtNetBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetBillActionPerformed

    private void cmbQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQtyActionPerformed
        // TODO add your handling code here:
        
        txtTotal.setText(String.valueOf(Integer.parseInt(txtPrice.getText().toString())*Integer.parseInt(cmbQty.getSelectedItem().toString())));
    }//GEN-LAST:event_cmbQtyActionPerformed

    private void RbtnDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnDebitActionPerformed
        // TODO add your handling code here:
        txtDiscount.setText("No Discount");
        txtNetBill.setText(txtTotal.getText().toString());
    }//GEN-LAST:event_RbtnDebitActionPerformed

    private void RbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnCashActionPerformed
        // TODO add your handling code here:
        txtDiscount.setText("3% ");

        double dis = Double.parseDouble(txtSubTotal.getText().toString())*0.03;
        double netbill = Double.parseDouble(txtSubTotal.getText().toString())-dis;
        txtNetBill.setText(String.valueOf(netbill));
        
    }//GEN-LAST:event_RbtnCashActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        Object o[] = {cmbItemId.getSelectedItem().toString(),
          txtName.getText().toString(),
            txtPrice.getText().toString(),
                txtCategory.getText().toString(),
                    txtBrand.getText().toString(),
                        cmbQty.getSelectedItem().toString(),
                            txtUnit.getText().toString(),
                                txtTotal.getText().toString()};
        model.addRow(o);
        
        txtSubTotal.setText(String.valueOf(/*Integer.parseInt(txtSubTotal.getText().toString())+*/Integer.parseInt(txtTotal.getText().toString())));
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CContactNo;
    private javax.swing.JLabel CContactNo1;
    private javax.swing.JLabel CContactNo10;
    private javax.swing.JLabel CContactNo11;
    private javax.swing.JLabel CContactNo12;
    private javax.swing.JLabel CContactNo2;
    private javax.swing.JLabel CContactNo3;
    private javax.swing.JLabel CContactNo4;
    private javax.swing.JLabel CContactNo5;
    private javax.swing.JLabel CContactNo6;
    private javax.swing.JLabel CContactNo7;
    private javax.swing.JLabel CContactNo8;
    private javax.swing.JLabel CContactNo9;
    private javax.swing.JLabel CID;
    private javax.swing.JLabel CReceiptNo;
    private javax.swing.JLabel CReceiptNo1;
    private javax.swing.JLabel CReceiptNo2;
    private javax.swing.JRadioButton RbtnCash;
    private javax.swing.JRadioButton RbtnDebit;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TextCId;
    private javax.swing.JTextField TextCName;
    private javax.swing.JTextField TextCReceiptNo;
    private javax.swing.JTextField TextContactId;
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbItemId;
    private javax.swing.JComboBox<String> cmbQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDATE;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNetBill;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSubTotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
