/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.stage.FileChooser;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Expert
 */
public class ItemManagement extends javax.swing.JFrame {

    DBConn DB = new DBConn();    
    File myfile;
    
    /**
     * Creates new form ItemManagement
     */
    public ItemManagement() {
        initComponents();
        btnSave.setVisible(false);
        btnUpdate.setVisible(false);
        btnDelete.setVisible(false);
        
    }
    public ItemManagement(String MODE) throws SQLException
    {
        initComponents();
        btnSave.setVisible(false);
        btnUpdate.setVisible(false);
        btnDelete.setVisible(false);
        btnSearch.setVisible(false);
        
        if(MODE.equalsIgnoreCase("New"))
                {
                    btnSave.setVisible(true);
                }
        if(MODE.equalsIgnoreCase("Update"))
        {
            btnUpdate.setVisible(true);
        }
        if(MODE.equals("Delete"))
        {
            btnDelete.setVisible(true);
        }
        if(MODE.equals("View"))
        {
            btnSearch.setVisible(true);
        }
        
        
        //coddin for table view data
        ResultSet myrs;
        int dd1=0; String ddll=null;//int ddll=0;
        String dd=null;
        DefaultTableModel model = (DefaultTableModel) tblItem.getModel();
        DB.opencon();
        myrs = DB.select("select * from compshopitem");
        while(myrs.next())
        {
            Object o[] = { myrs.getString("name"),myrs.getString("category"),myrs.getString("Units"),myrs.getString("itemid"),myrs.getString("brand"),myrs.getString("stock"),myrs.getString("price") };
            model.addRow(o);
        }
        DB.closeCon();
        
        //  CODE FOR DATE AND TIME USING CALENDER CLASS IN CONSTRUCTIONN
        
        
        Calendar c = Calendar.getInstance();  //for calling sytestem calender object
        dd1 = c.get(Calendar.DAY_OF_MONTH);
        if(dd1<10)
        {
            dd="0"+dd1;
        }
        else
        {
            dd=""+dd1;
        }
        String mm = String.valueOf(c.get(Calendar.MONTH)+1);
        String yy = String.valueOf(c.get(Calendar.YEAR));
        
        int hr = c.get(Calendar.HOUR);
        if(hr>12)
        {
            hr=hr-12;
        }
       /* if(hr>10)
        {
            ddll ="0"+hr;
        }
        else
        {
            ddll=""+hr;
        }*/
        
        String min = String.valueOf(c.get(Calendar.MINUTE));
        
        lblDate.setText(dd +"/" +mm+ "/" +yy +"   "+ hr +":" +min);
        
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        cmbBrand = new javax.swing.JComboBox<>();
        TextItemId = new javax.swing.JTextField();
        TextName = new javax.swing.JTextField();
        TextStock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbUnit = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TextPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Item Managemet");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 112);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Category : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(31, 41, 109, 32);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Item Id : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(31, 164, 109, 32);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Name :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(31, 224, 55, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("In Stock");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(31, 287, 66, 22);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Brand : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(31, 92, 63, 22);

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptops", "Desktop", "CPU", "HARDDISK", "KEYBOARD", "MOUSE", "PENDRIVES", "PRINTERS", " ", " " }));
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });
        jPanel2.add(cmbCategory);
        cmbCategory.setBounds(152, 47, 208, 32);

        cmbBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LENOVO", "HP", "DELL", "ACENTURE", "ASUS", "APPLE", "SANDISK", " " }));
        cmbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBrandActionPerformed(evt);
            }
        });
        jPanel2.add(cmbBrand);
        cmbBrand.setBounds(152, 92, 208, 22);

        TextItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextItemIdActionPerformed(evt);
            }
        });
        jPanel2.add(TextItemId);
        TextItemId.setBounds(152, 164, 208, 34);
        jPanel2.add(TextName);
        TextName.setBounds(152, 219, 208, 34);

        TextStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextStockActionPerformed(evt);
            }
        });
        jPanel2.add(TextStock);
        TextStock.setBounds(152, 275, 208, 34);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("IMAGE");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(480, 40, 58, 22);

        lblImage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblImage.setText("UPLOAD IMAGE");
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
        });
        jPanel2.add(lblImage);
        lblImage.setBounds(450, 70, 337, 292);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("UNITS:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(31, 127, 59, 22);

        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 1", " 2", " 3", " 4", " 5" }));
        jPanel2.add(cmbUnit);
        cmbUnit.setBounds(152, 127, 208, 22);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("PRICE");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(42, 341, 55, 22);
        jPanel2.add(TextPrice);
        TextPrice.setBounds(152, 336, 208, 34);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);
        btnBack.setBounds(410, 410, 130, 50);

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("SAVE");
        btnSave.setOpaque(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);
        btnSave.setBounds(210, 410, 130, 50);

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("DELETE");
        btnDelete.setOpaque(false);
        jPanel2.add(btnDelete);
        btnDelete.setBounds(210, 410, 130, 50);

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("UPDATE");
        btnUpdate.setOpaque(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(210, 410, 130, 50);

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("SEARCH");
        btnSearch.setOpaque(false);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(210, 410, 130, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 119, 820, 490);

        jPanel4.setBackground(new java.awt.Color(0, 153, 204));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Brand", "Units", "ItemId", "Name", "Stock", "price"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 609, 820, 150);

        setSize(new java.awt.Dimension(840, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void TextItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextItemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextItemIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            DB.opencon();
            
            PreparedStatement pstmt = DBConn.con.prepareStatement("insert into compshopitem values(?,?,?,?,?,?,?,?)");
            pstmt.setString(1, TextName.getText().toString());
            pstmt.setString(2,cmbCategory.getSelectedItem().toString());
            pstmt.setString(3, cmbUnit.getSelectedItem().toString());
            pstmt.setString(4,TextItemId.getText().toString());
            pstmt.setString(5,cmbBrand.getSelectedItem().toString());
            pstmt.setString(6, TextStock.getText().toString());
            pstmt.setString(7, TextPrice.getText().toString());
            
            FileInputStream fin = new FileInputStream(myfile.getAbsolutePath());   //for converting image into binary
            pstmt.setBinaryStream(8, fin, fin.available());
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Item Data Added Successfully..");
            
            //TextName.requestFocus();
            DB.closeCon();
                        
            
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(ItemManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ItemManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        // TODO add your handling code here:
        
         //create file
        JFileChooser jfc = new JFileChooser(); //create JFilsChooser Obj
        
        FileNameExtensionFilter fnm = new FileNameExtensionFilter("*.images","jpng","png","gif"); //to change file to image extensionn
        jfc.addChoosableFileFilter(fnm);
        
        int result = jfc.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION) //when you click on OK button then this operation performed
        {
            System.out.println("File Selected...");
            myfile = jfc.getSelectedFile(); // for current selected file
            
            System.out.println("PATH :  "+ myfile.getPath()); // for displaying file Location(PATH)
            
            Image myimage = new ImageIcon(myfile.getAbsolutePath()).getImage().getScaledInstance(lblImage.getWidth(),lblImage.getHeight(),Image.SCALE_SMOOTH);//to set image into label size to fit           
            Icon myicon = new ImageIcon(myimage); // convertion image to icon
            lblImage.setIcon(myicon);
            
        }
        else
        {
            System.out.println("FIle NOT Selected..");
            
        }
        
        
        
    }//GEN-LAST:event_lblImageMouseClicked

    private void cmbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBrandActionPerformed

    private void TextStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextStockActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            // TODO add your handling code here:
            ResultSet myrs;
            DB.opencon();
            
            myrs = DB.select(" select * from compshopitem where itemid= '"+TextItemId.getText().toString()+"' ");
            myrs.next();
            cmbBrand.setSelectedItem(myrs.getString("brand"));
            TextName.setText(myrs.getString("name"));
            TextPrice.setText(myrs.getString("price"));
            TextStock.setText(myrs.getString("stock"));
            
            Blob b = myrs.getBlob("image");             //for converting binary to image
            Image myimg = new ImageIcon(b.getBytes(1, (int) b.length())).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(),Image.SCALE_SMOOTH);
            Icon myicon = new ImageIcon(myimg);
            lblImage.setIcon(myicon);
            
            DB.closeCon();
            
            
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(ItemManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        // TODO add your handling code here:
      DefaultTableModel model = (DefaultTableModel) tblItem.getModel();
      TextItemId.setText((String) model.getValueAt(tblItem.getSelectedRow(),tblItem.getSelectedColumn()));
      TextName.setText((String) model.getValueAt(tblItem.getSelectedRow(),tblItem.getSelectedColumn()+1));
      TextStock.setText((String) model.getValueAt(tblItem.getSelectedRow(),tblItem.getSelectedColumn()+2));
      TextPrice.setText((String) model.getValueAt(tblItem.getSelectedRow(),tblItem.getSelectedColumn()+3));
    }//GEN-LAST:event_tblItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextItemId;
    private javax.swing.JTextField TextName;
    private javax.swing.JTextField TextPrice;
    private javax.swing.JTextField TextStock;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbBrand;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
